language: objective-c
rvm: 2.1.0
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - brew update
  - cd Tests && pod install && cd $TRAVIS_BUILD_DIR
script: rake test
